/* HSK Level 9 Character Data (400 characters) */
/* Generated by build/gen_hsk_data.js */
var HSK_DATA_9 = {
 "屠": {
  "pinyin": "tú",
  "english": "",
  "words": [
   {
    "w": "屠杀",
    "p": "túshā",
    "en": "to massacre, massacre, bloodbath, carnage"
   }
  ]
 },
 "妥": {
  "pinyin": "tuǒ",
  "english": "suitable, adequate, ready, settled",
  "words": [
   {
    "w": "妥当",
    "p": "tuǒdang",
    "en": "appropriate, proper, ready"
   },
   {
    "w": "妥善",
    "p": "tuǒshàn",
    "en": "appropriate, proper"
   },
   {
    "w": "妥协",
    "p": "tuǒxié",
    "en": "come to terms, compromise"
   },
   {
    "w": "稳妥",
    "p": "wěntuǒ",
    "en": "dependable"
   }
  ]
 },
 "婉": {
  "pinyin": "wǎn",
  "english": "",
  "words": [
   {
    "w": "委婉",
    "p": "wěiwǎn",
    "en": "tactful, euphemistic, (of voice etc) suave, soft"
   }
  ]
 },
 "妄": {
  "pinyin": "wàng",
  "english": "",
  "words": [
   {
    "w": "妄想",
    "p": "wàngxiǎng",
    "en": "to attempt vainly, a vain attempt, delusion"
   }
  ]
 },
 "巫": {
  "pinyin": "wū",
  "english": "",
  "words": [
   {
    "w": "巫婆",
    "p": "wūpó",
    "en": "witch, sorceress, female shaman"
   }
  ]
 },
 "勿": {
  "pinyin": "wù",
  "english": "do not"
 },
 "嬉": {
  "pinyin": "xī",
  "english": "",
  "words": [
   {
    "w": "嬉笑",
    "p": "xīxiào",
    "en": "to be laughing and playing, to giggle"
   }
  ]
 },
 "侠": {
  "pinyin": "xiá",
  "english": "",
  "words": [
   {
    "w": "侠义",
    "p": "xiáyì",
    "en": "chivalrous, chivalry, knight-errantry"
   }
  ]
 },
 "厢": {
  "pinyin": "xiāng",
  "english": "",
  "words": [
   {
    "w": "车厢",
    "p": "chēxiāng",
    "en": "carriage, CL:節|节[jie2]"
   }
  ]
 },
 "孝": {
  "pinyin": "xiào",
  "english": "",
  "words": [
   {
    "w": "孝敬",
    "p": "xiàojìng",
    "en": "to show filial respect, to give presents (to one's elders or superiors), to support one's aged parents"
   },
   {
    "w": "孝顺",
    "p": "xiàoshun",
    "en": "filial, show filial obedience"
   }
  ]
 },
 "嗅": {
  "pinyin": "xiù",
  "english": "",
  "words": [
   {
    "w": "嗅觉",
    "p": "xiùjué",
    "en": "sense of smell"
   }
  ]
 },
 "吁": {
  "pinyin": "yù",
  "english": "",
  "words": [
   {
    "w": "呼吁",
    "p": "hūyù",
    "en": "to call on (sb to do sth), to appeal (to), an appeal"
   }
  ]
 },
 "婿": {
  "pinyin": "xu",
  "english": "",
  "words": [
   {
    "w": "女婿",
    "p": "nǚxu",
    "en": "daughter's husband, son-in-law"
   }
  ]
 },
 "喧": {
  "pinyin": "xuān",
  "english": "",
  "words": [
   {
    "w": "喧哗",
    "p": "xuānhuá",
    "en": "hubbub, clamor, to make a racket"
   },
   {
    "w": "喧闹",
    "p": "xuānnào",
    "en": "to make a noise, noisy"
   }
  ]
 },
 "勋": {
  "pinyin": "xūn",
  "english": "",
  "words": [
   {
    "w": "勋章",
    "p": "xūnzhāng",
    "en": "medal, decoration"
   }
  ]
 },
 "丫": {
  "pinyin": "yā",
  "english": "",
  "words": [
   {
    "w": "丫头",
    "p": "yātou",
    "en": "girl, servant girl, (used deprecatingly, but sometimes also as a term of endearment)"
   }
  ]
 },
 "哑": {
  "pinyin": "yǎ",
  "english": "(onom.) sound of cawing, sound of infant learning to talk, variant of 呀[ya1], dumb, mute, hoarse, husky, unexploded (of artillery shell etc)"
 },
 "倚": {
  "pinyin": "yǐ",
  "english": "to lean on, to rely upon"
 },
 "亦": {
  "pinyin": "yì",
  "english": "also, too",
  "words": [
   {
    "w": "不亦乐乎",
    "p": "bùyìlèhū",
    "en": "lit. isn't that a joy? (quote from Confucius), fig. (jocularly) extremely, awfully"
   }
  ]
 },
 "姻": {
  "pinyin": "yīn",
  "english": "",
  "words": [
   {
    "w": "婚姻",
    "p": "hūnyīn",
    "en": "connubiality, wedlock, marital, union, marriage, married couple, matrimonial, match, man and wife, matrimony"
   }
  ]
 },
 "婴": {
  "pinyin": "yīngé",
  "english": "",
  "words": [
   {
    "w": "婴儿",
    "p": "yīngér",
    "en": "babe, baby infant, wean, neonate, papoose, nestling, parvulus, baby, cheeper, child, bantling, nursling, bambino, infant, nurseling, infantile, suckling, chrisom"
   }
  ]
 },
 "佣": {
  "pinyin": "yōng",
  "english": "",
  "words": [
   {
    "w": "雇佣",
    "p": "gùyōng",
    "en": "to employ, to hire"
   }
  ]
 },
 "佑": {
  "pinyin": "yòu",
  "english": "",
  "words": [
   {
    "w": "保佑",
    "p": "bǎoyòu",
    "en": "to bless and protect, blessing"
   }
  ]
 },
 "喻": {
  "pinyin": "yù",
  "english": "",
  "words": [
   {
    "w": "比喻",
    "p": "bǐyù",
    "en": "metaphor, analogy"
   },
   {
    "w": "家喻户晓",
    "p": "jiāyù-hùxiǎo",
    "en": "understood by everyone (idiom), well known, a household name"
   }
  ]
 },
 "冤": {
  "pinyin": "yuān",
  "english": "injustice, grievance, wrong, old variant of 冤[yuan1]",
  "words": [
   {
    "w": "冤枉",
    "p": "yuānwang",
    "en": "to accuse wrongly, to treat unjustly, injustice, wronged, not worthwhile"
   }
  ]
 },
 "岳": {
  "pinyin": "yuè",
  "english": "",
  "words": [
   {
    "w": "岳父",
    "p": "yuèfù",
    "en": "wife's father, father-in-law"
   },
   {
    "w": "岳母",
    "p": "yuèmǔ",
    "en": "wife's mother, mother-in-law"
   }
  ]
 },
 "兆": {
  "pinyin": "zhào",
  "english": "",
  "words": [
   {
    "w": "预兆",
    "p": "yùzhào",
    "en": "omen, sign (of sth yet to occur), prior indication, to foreshadow"
   },
   {
    "w": "兆头",
    "p": "zhàotou",
    "en": "omen, portent, sign"
   }
  ]
 },
 "侦": {
  "pinyin": "zhēn",
  "english": "",
  "words": [
   {
    "w": "侦察",
    "p": "zhēnchá",
    "en": "to investigate a crime, to scout, to reconnoiter, reconnaissance, detection, a scout"
   }
  ]
 },
 "峙": {
  "pinyin": "zhì",
  "english": "",
  "words": [
   {
    "w": "对峙",
    "p": "duìzhì",
    "en": "to stand opposite, to confront, confrontation"
   }
  ]
 },
 "仲": {
  "pinyin": "zhòng",
  "english": "",
  "words": [
   {
    "w": "仲裁",
    "p": "zhòngcái",
    "en": "arbitration"
   }
  ]
 },
 "坠": {
  "pinyin": "zhuì",
  "english": "to fall, to drop, to weigh down",
  "words": [
   {
    "w": "下坠",
    "p": "xiàzhuì",
    "en": "Fall"
   },
   {
    "w": "摇摇欲坠",
    "p": "yáoyáo-yùzhuì",
    "en": "tottering, on the verge of collapse"
   }
  ]
 },
 "卓": {
  "pinyin": "zhuó",
  "english": "",
  "words": [
   {
    "w": "卓越",
    "p": "zhuóyuè",
    "en": "excel, excel at, brilliant, shine, surpassing, paramount, shine at, outstanding"
   }
  ]
 },
 "兹": {
  "pinyin": "cí",
  "english": "now, here, this, time, year"
 },
 "姿": {
  "pinyin": "zī",
  "english": "",
  "words": [
   {
    "w": "姿态",
    "p": "zītài",
    "en": "mannerism, set, stance, pose, attitude, affectation, port, shadow, likeness, carriage, posture, position, movement, gesture, tournure, sort"
   },
   {
    "w": "姿势",
    "p": "zīshì",
    "en": "mannerism, plant, poise, motion, pose, attitude, sign, affectation, port, likeness, carriage, posture, position, setup, gesticulation, gesture, seat"
   }
  ]
 },
 "佐": {
  "pinyin": "zuǒ",
  "english": "",
  "words": [
   {
    "w": "佐料",
    "p": "zuǒliào",
    "en": "condiments, seasoning"
   }
  ]
 },
 "掰": {
  "pinyin": "bāi",
  "english": "to break off or break open sth with one's hands, (fig.) to break off (a relationship)"
 },
 "毙": {
  "pinyin": "bì",
  "english": "",
  "words": [
   {
    "w": "枪毙",
    "p": "qiāngbì",
    "en": "to execute by firing squad, to shoot dead, fig. to discard, to get rid of"
   }
  ]
 },
 "憋": {
  "pinyin": "biē",
  "english": "to choke, to stifle, to restrain, to hold back, to hold in (urine), to hold (one's breath)"
 },
 "惭": {
  "pinyin": "cán",
  "english": "",
  "words": [
   {
    "w": "惭愧",
    "p": "cánkuì",
    "en": "ashamed"
   }
  ]
 },
 "槽": {
  "pinyin": "cáo",
  "english": "trough, manger, groove, channel, (Tw) (computing) hard drive",
  "words": [
   {
    "w": "水槽",
    "p": "shuǐcáo",
    "en": "sink"
   },
   {
    "w": "跳槽",
    "p": "tiào cáo",
    "en": "to change jobs, job-hopping"
   }
  ]
 },
 "掺": {
  "pinyin": "càn",
  "english": "variant of 攙|搀[chan1], to mix, to grasp"
 },
 "斥": {
  "pinyin": "chì",
  "english": "",
  "words": [
   {
    "w": "排斥",
    "p": "páichì",
    "en": "repel, exclude, reject"
   }
  ]
 },
 "捶": {
  "pinyin": "chuí",
  "english": "to beat with the fist, to hammer, to cudgel, variant of 捶[chui2]"
 },
 "挫": {
  "pinyin": "cuò",
  "english": "",
  "words": [
   {
    "w": "挫折",
    "p": "cuòzhé",
    "en": "frustratio, rebuff, defeat, founder, frustration, reverse, breakdown, blight, setback, throwback, abortion, backset, flivver, dash, cross"
   },
   {
    "w": "抑扬顿挫",
    "p": "yìyáng-dùncuò",
    "en": "see 頓挫抑揚|顿挫抑扬[dun4 cuo4 yi4 yang2]"
   }
  ]
 },
 "怠": {
  "pinyin": "dài",
  "english": "",
  "words": [
   {
    "w": "怠工",
    "p": "dài gōng",
    "en": "to slacken off in one's work, to go slow (as a form of strike)"
   },
   {
    "w": "怠慢",
    "p": "dàimàn",
    "en": "to slight, to neglect"
   }
  ]
 },
 "惦": {
  "pinyin": "diàn",
  "english": "",
  "words": [
   {
    "w": "惦记",
    "p": "diànji",
    "en": "to think of, to keep thinking about, to be concerned about"
   }
  ]
 },
 "敦": {
  "pinyin": "dūn",
  "english": "",
  "words": [
   {
    "w": "敦厚",
    "p": "dūnhòu",
    "en": "genuine, honest and sincere"
   },
   {
    "w": "敦促",
    "p": "dūncù",
    "en": "to press, to urge, to hasten"
   }
  ]
 },
 "敷": {
  "pinyin": "fū",
  "english": "to spread, to lay out, to apply (powder, ointment etc), sufficient (to cover), enough"
 },
 "杠": {
  "pinyin": "gàng",
  "english": "",
  "words": [
   {
    "w": "杠铃",
    "p": "gànglíng",
    "en": "barbell"
   }
  ]
 },
 "戈": {
  "pinyin": "gē",
  "english": "",
  "words": [
   {
    "w": "干戈",
    "p": "gāngē",
    "en": "weapons of war, arms"
   },
   {
    "w": "戈壁",
    "p": "gēbì",
    "en": "Gobi (desert)"
   }
  ]
 },
 "棺": {
  "pinyin": "guān",
  "english": "",
  "words": [
   {
    "w": "棺材",
    "p": "guāncai",
    "en": "coffin, CL:具[ju4],口[kou3]"
   }
  ]
 },
 "涵": {
  "pinyin": "hán",
  "english": "",
  "words": [
   {
    "w": "涵盖",
    "p": "hángài",
    "en": "cover, include"
   },
   {
    "w": "涵义",
    "p": "hányì",
    "en": "content, meaning, connotation, implication"
   },
   {
    "w": "内涵",
    "p": "nèihán",
    "en": "intension, comprehension, intention, connotation"
   },
   {
    "w": "蕴涵",
    "p": "yùnhán",
    "en": "to contain, to accumulate, to embrace, implicit condition, implication, entailment"
   }
  ]
 },
 "捍": {
  "pinyin": "hàn",
  "english": "",
  "words": [
   {
    "w": "捍卫",
    "p": "hànwèi",
    "en": "to defend, to uphold, to safeguard"
   }
  ]
 },
 "棘": {
  "pinyin": "jí",
  "english": "",
  "words": [
   {
    "w": "棘手",
    "p": "jíshǒu",
    "en": "thorny (problem), intractable"
   },
   {
    "w": "荆棘",
    "p": "jīngjí",
    "en": "thistles and thorns, brambles, thorny undergrowth"
   }
  ]
 },
 "歼": {
  "pinyin": "jiān",
  "english": "",
  "words": [
   {
    "w": "歼灭",
    "p": "jiānmiè",
    "en": "to wipe out, to crush, to annihilate"
   }
  ]
 },
 "拣": {
  "pinyin": "jiǎn",
  "english": "to choose, to pick, to sort out, to pick up"
 },
 "柬": {
  "pinyin": "jiǎn",
  "english": "",
  "words": [
   {
    "w": "请柬",
    "p": "qǐngjiǎn",
    "en": "invitation card, written invitation"
   }
  ]
 },
 "浆": {
  "pinyin": "jiāng",
  "english": "",
  "words": [
   {
    "w": "豆浆",
    "p": "dòujiāng",
    "en": "soy milk"
   }
  ]
 },
 "楷": {
  "pinyin": "kǎi",
  "english": "",
  "words": [
   {
    "w": "楷模",
    "p": "kǎimó",
    "en": "model, example"
   }
  ]
 },
 "槛": {
  "pinyin": "kǎn",
  "english": "",
  "words": [
   {
    "w": "门槛",
    "p": "ménkǎn",
    "en": "doorstep, sill, threshold, fig. knack or trick (esp. scheme to get sth cheaper)"
   }
  ]
 },
 "抠": {
  "pinyin": "kōu",
  "english": "to dig out, to pick out (with one's fingers), to carve, to cut, to study meticulously, to lift one's clothes, stingy, miserly"
 },
 "溃": {
  "pinyin": "kuì",
  "english": "",
  "words": [
   {
    "w": "崩溃",
    "p": "bēngkuì",
    "en": "collapse, fall apart"
   }
  ]
 },
 "昆": {
  "pinyin": "kūn",
  "english": "",
  "words": [
   {
    "w": "昆虫",
    "p": "kūnchóng",
    "en": "bug, creeper, hexapod, coreid, insect, dor, coreid bug"
   }
  ]
 },
 "拦": {
  "pinyin": "lán",
  "english": "to block sb's path, to obstruct, to flag down (a taxi)",
  "words": [
   {
    "w": "阻拦",
    "p": "zǔlán",
    "en": "to stop, to obstruct"
   }
  ]
 },
 "捞": {
  "pinyin": "lāo",
  "english": "to fish up, to dredge up",
  "words": [
   {
    "w": "打捞",
    "p": "dǎlāo",
    "en": "to salvage, to dredge, to fish out (person or object from the sea)"
   }
  ]
 },
 "涝": {
  "pinyin": "lào",
  "english": "flooded"
 },
 "愣": {
  "pinyin": "lèng",
  "english": "to look distracted, to stare blankly, distracted, blank, (coll.) unexpectedly, rash, rashly",
  "words": [
   {
    "w": "发愣",
    "p": "fālèng",
    "en": "to daydream, in a daze"
   }
  ]
 },
 "潦": {
  "pinyin": "liáo",
  "english": "",
  "words": [
   {
    "w": "潦草",
    "p": "liáocǎo",
    "en": "careless, slovenly, illegible (of handwriting)"
   }
  ]
 },
 "拎": {
  "pinyin": "līn",
  "english": "to lift, to carry in one's hand, Taiwan pr. [ling1]"
 },
 "浏": {
  "pinyin": "liú",
  "english": "",
  "words": [
   {
    "w": "浏览器",
    "p": "liúlǎnqì",
    "en": "browser (software)"
   },
   {
    "w": "浏览",
    "p": "liúlǎn",
    "en": "thumb, glance, riff, scan, riffle, leaf, riffle through, pass over, browse, dip_into, skim, skim through, run_through, flick, flip, dip into, glance over, peruse"
   }
  ]
 },
 "氓": {
  "pinyin": "máng",
  "english": "",
  "words": [
   {
    "w": "流氓",
    "p": "liúmáng",
    "en": "roughscuff, rip, yobbo, badmash, swashbuckler, rascal, riffraff, scamp, raff, rapscallion, rogue, rowdy, hooliganism, cur, picaroon, varmint, yobo, ruffian, hector, roughneck, gaolbird, scalawag, gorilla, no-good, scallywag, hoodlum, limmer, tearaway, blackguard, picaro, hooligan, hessian, bullyboy, rascallion, indecency, bully, plug-ugly, shoulder-hitter, dingbat, caird, tough, varlet, sc"
   }
  ]
 },
 "昧": {
  "pinyin": "mèi",
  "english": "",
  "words": [
   {
    "w": "冒昧",
    "p": "màomèi",
    "en": "bold, presumptuous, to take the liberty of"
   }
  ]
 },
 "泌": {
  "pinyin": "mì",
  "english": "",
  "words": [
   {
    "w": "分泌",
    "p": "fēnmì",
    "en": "to secrete, secretion"
   }
  ]
 },
 "渺": {
  "pinyin": "miǎo",
  "english": "",
  "words": [
   {
    "w": "渺小",
    "p": "miǎoxiǎo",
    "en": "minute, tiny, negligible, insignificant"
   }
  ]
 },
 "拟": {
  "pinyin": "nǐ",
  "english": "intend, plan",
  "words": [
   {
    "w": "模拟",
    "p": "mónǐ",
    "en": "imitate, simulate"
   },
   {
    "w": "拟定",
    "p": "nǐdìng",
    "en": "formulate, conjecture"
   },
   {
    "w": "虚拟",
    "p": "xūnǐ",
    "en": "conjecture, fictitious, pseudo, suppositional, fantasy"
   }
  ]
 },
 "拧": {
  "pinyin": "níng",
  "english": "to pinch, wring, mistake, to twist, stubborn"
 },
 "殴": {
  "pinyin": "ōu",
  "english": "",
  "words": [
   {
    "w": "殴打",
    "p": "ōudǎ",
    "en": "beat up, come to blows"
   }
  ]
 },
 "攀": {
  "pinyin": "pān",
  "english": "",
  "words": [
   {
    "w": "攀升",
    "p": "pānshēng",
    "en": "to clamber up, (of prices etc) to rise"
   }
  ]
 },
 "沛": {
  "pinyin": "pèi",
  "english": "",
  "words": [
   {
    "w": "充沛",
    "p": "chōngpèi",
    "en": "abundant, plentiful, vigorous"
   }
  ]
 },
 "抨": {
  "pinyin": "pēng",
  "english": "",
  "words": [
   {
    "w": "抨击",
    "p": "pēngjī",
    "en": "attack (in speech/writing), assail"
   }
  ]
 },
 "捧": {
  "pinyin": "pěng",
  "english": "hold/carry sth. level in both hands, boost, boast, exalt, flatter",
  "words": [
   {
    "w": "吹捧",
    "p": "chuīpěng",
    "en": "to flatter, to laud sb's accomplishments, adulation"
   },
   {
    "w": "捧场",
    "p": "pěng chǎng",
    "en": "to cheer on (originally esp. as paid stooge), to root for sb, to sing sb's praises, to flatter"
   }
  ]
 },
 "撇": {
  "pinyin": "piē",
  "english": "to cast away, to fling aside, to throw, to cast, left-slanting downward brush stroke (calligraphy)"
 },
 "沏": {
  "pinyin": "qī",
  "english": "to steep (tea)"
 },
 "歧": {
  "pinyin": "qí",
  "english": "",
  "words": [
   {
    "w": "分歧",
    "p": "fēnqí",
    "en": "divergent, difference (of opinion, position), disagreement, bifurcation (math.)"
   },
   {
    "w": "歧视",
    "p": "qíshì",
    "en": "treat with bias, despise"
   }
  ]
 },
 "掐": {
  "pinyin": "qiā",
  "english": "to pick (flowers), to pinch, to nip, to pinch off, to clutch, (slang) to fight"
 },
 "撬": {
  "pinyin": "qiào",
  "english": "to lift, to pry open, to lever open"
 },
 "惹": {
  "pinyin": "rě",
  "english": "provoke"
 },
 "溶": {
  "pinyin": "róng",
  "english": "",
  "words": [
   {
    "w": "溶解",
    "p": "róngjiě",
    "en": "to dissolve"
   }
  ]
 },
 "捎": {
  "pinyin": "shāo",
  "english": "to bring sth to sb, to deliver"
 },
 "慑": {
  "pinyin": "shè",
  "english": "",
  "words": [
   {
    "w": "威慑",
    "p": "wēishè",
    "en": "to cower by military force, deterrence"
   }
  ]
 },
 "抒": {
  "pinyin": "shū",
  "english": "",
  "words": [
   {
    "w": "抒情",
    "p": "shūqíng",
    "en": "to express emotion, lyric"
   }
  ]
 },
 "枢": {
  "pinyin": "shū",
  "english": "",
  "words": [
   {
    "w": "枢纽",
    "p": "shūniǔ",
    "en": "hub (e.g. of traffic network), hinge, pivot, fulcrum"
   }
  ]
 },
 "恕": {
  "pinyin": "shù",
  "english": "",
  "words": [
   {
    "w": "宽恕",
    "p": "kuānshù",
    "en": "to forgive, forgiveness"
   },
   {
    "w": "饶恕",
    "p": "ráoshù",
    "en": "to forgive, to pardon, to spare"
   }
  ]
 },
 "拴": {
  "pinyin": "shuān",
  "english": "to tie up"
 },
 "涮": {
  "pinyin": "shuàn",
  "english": "to rinse, to trick, to fool sb, to cook by dipping finely sliced ingredients briefly in boiling water or soup (generally done at the dining table)"
 },
 "溯": {
  "pinyin": "sù",
  "english": "",
  "words": [
   {
    "w": "追溯",
    "p": "zhuīsù",
    "en": "lit. to go upstream, to trace sth back to, to date from"
   }
  ]
 },
 "汰": {
  "pinyin": "tài",
  "english": "",
  "words": [
   {
    "w": "淘汰",
    "p": "táotài",
    "en": "weed out, competition, eliminate through selection, supersede, superannuate, weed, eliminate through selection or competition, screen_out, eliminate through competition, eliminate through selection/competition, fall into disuse, die out, eliminate, comb out, weed_out, selective"
   }
  ]
 },
 "潭": {
  "pinyin": "tán",
  "english": "",
  "words": [
   {
    "w": "泥潭",
    "p": "nítán",
    "en": "quagmire"
   }
  ]
 },
 "涕": {
  "pinyin": "tì",
  "english": "",
  "words": [
   {
    "w": "鼻涕",
    "p": "bítì",
    "en": "nasal mucus, snivel"
   }
  ]
 },
 "惕": {
  "pinyin": "tì",
  "english": "",
  "words": [
   {
    "w": "警惕",
    "p": "jǐngtì",
    "en": "to be on the alert, vigilant, alert, on guard, to warn"
   }
  ]
 },
 "捅": {
  "pinyin": "tǒng",
  "english": "to stab, to poke, to prod, to nudge, to disclose"
 },
 "桶": {
  "pinyin": "tǒng",
  "english": "bucket, (trash) can, barrel (of oil etc), CL:個|个[ge4],隻|只[zhi1]",
  "words": [
   {
    "w": "马桶",
    "p": "mǎtǒng",
    "en": "chamber pot, wooden pan used as toilet, toilet bowl"
   }
  ]
 },
 "歪": {
  "pinyin": "wāi",
  "english": "askew, at a crooked angle, devious, noxious, (coll.) to lie on one's side, to sprain (one's ankle) (Tw)",
  "words": [
   {
    "w": "歪曲",
    "p": "wāiqū",
    "en": "to distort, to misrepresent"
   }
  ]
 },
 "惋": {
  "pinyin": "wǎn",
  "english": "",
  "words": [
   {
    "w": "惋惜",
    "p": "wǎnxī",
    "en": "to regret, to feel that it is a great pity, to feel sorry for sb"
   }
  ]
 },
 "汪": {
  "pinyin": "wāng",
  "english": "",
  "words": [
   {
    "w": "汪洋",
    "p": "wāngyáng",
    "en": "vast body of water, CL:片[pian4]"
   }
  ]
 },
 "枉": {
  "pinyin": "wang",
  "english": "",
  "words": [
   {
    "w": "冤枉",
    "p": "yuānwang",
    "en": "to accuse wrongly, to treat unjustly, injustice, wronged, not worthwhile"
   }
  ]
 },
 "涡": {
  "pinyin": "wō",
  "english": "",
  "words": [
   {
    "w": "旋涡",
    "p": "xuánwō",
    "en": "spiral, whirlpool, eddy, vortex"
   }
  ]
 },
 "捂": {
  "pinyin": "wǔ",
  "english": "to enclose, to cover with the hand (one's eyes, nose or ears), to cover up (an affair), contrary, to contradict"
 },
 "晤": {
  "pinyin": "wù",
  "english": "",
  "words": [
   {
    "w": "会晤",
    "p": "huìwù",
    "en": "to meet, meeting, conference"
   }
  ]
 },
 "昔": {
  "pinyin": "xī",
  "english": "",
  "words": [
   {
    "w": "昔日",
    "p": "xīrì",
    "en": "formerly, in olden days"
   }
  ]
 },
 "淆": {
  "pinyin": "xiáo",
  "english": "",
  "words": [
   {
    "w": "混淆",
    "p": "hùnxiáo",
    "en": "to obscure, to confuse, to mix up, to blur, to mislead"
   }
  ]
 },
 "挟": {
  "pinyin": "xié",
  "english": "",
  "words": [
   {
    "w": "挟持",
    "p": "xiéchí",
    "en": "to seize"
   }
  ]
 },
 "旭": {
  "pinyin": "xù",
  "english": "",
  "words": [
   {
    "w": "旭日",
    "p": "xùrì",
    "en": "the rising sun"
   }
  ]
 },
 "恤": {
  "pinyin": "xù",
  "english": "",
  "words": [
   {
    "w": "抚恤",
    "p": "fǔxù",
    "en": "(of an organization that has a duty of care) to give financial support to relatives of sb who has died or suffered serious injury"
   }
  ]
 },
 "旬": {
  "pinyin": "xún",
  "english": "",
  "words": [
   {
    "w": "上旬",
    "p": "shàngxún",
    "en": "first third of a month"
   },
   {
    "w": "下旬",
    "p": "xiàxún",
    "en": "last third of the month"
   },
   {
    "w": "中旬",
    "p": "zhōngxún",
    "en": "middle third of a month"
   }
  ]
 },
 "椰": {
  "pinyin": "yē",
  "english": "",
  "words": [
   {
    "w": "椰子",
    "p": "yēzi",
    "en": "coconut"
   }
  ]
 },
 "殷": {
  "pinyin": "yīn",
  "english": "",
  "words": [
   {
    "w": "殷勤",
    "p": "yīnqín",
    "en": "politely, solicitously, eagerly attentive"
   }
  ]
 },
 "愚": {
  "pinyin": "yú",
  "english": "",
  "words": [
   {
    "w": "愚蠢",
    "p": "yúchǔn",
    "en": "silly, stupid"
   },
   {
    "w": "愚公移山",
    "p": "Yúgōng-yíshān",
    "en": "the old man moves mountains (idiom), fig. where there's a will, there's a way"
   }
  ]
 },
 "攒": {
  "pinyin": "zǎn",
  "english": "to bring together, to collect, to hoard, to accumulate, to save"
 },
 "渣": {
  "pinyin": "zhā",
  "english": "",
  "words": [
   {
    "w": "渣子",
    "p": "zhāzi",
    "en": "Slag"
   }
  ]
 },
 "杖": {
  "pinyin": "zhàng",
  "english": "",
  "words": [
   {
    "w": "禅杖",
    "p": "chánzhàng",
    "en": "the staff of a Buddhist monk"
   },
   {
    "w": "拐杖",
    "p": "guǎizhàng",
    "en": "crutches, crutch, walking stick"
   }
  ]
 },
 "拯": {
  "pinyin": "zhěng",
  "english": "",
  "words": [
   {
    "w": "拯救",
    "p": "zhěngjiù",
    "en": "spare, help, extricate, rescue, save, deliver"
   }
  ]
 },
 "旨": {
  "pinyin": "zhǐ",
  "english": "",
  "words": [
   {
    "w": "旨在",
    "p": "zhǐzài",
    "en": "to have as its purpose, to be intended to, to aim to (do sth)"
   },
   {
    "w": "宗旨",
    "p": "zōngzhǐ",
    "en": "animus, object, purpose, aim, religion, bearing"
   }
  ]
 },
 "挚": {
  "pinyin": "zhì",
  "english": "",
  "words": [
   {
    "w": "诚挚",
    "p": "chéngzhì",
    "en": "sincere, cordial"
   },
   {
    "w": "真挚",
    "p": "zhēnzhì",
    "en": "sincere, sincerity"
   }
  ]
 },
 "滞": {
  "pinyin": "zhì",
  "english": "",
  "words": [
   {
    "w": "滞后",
    "p": "zhìhòu",
    "en": "to lag behind"
   },
   {
    "w": "滞留",
    "p": "zhìliú",
    "en": "to detain, retention"
   }
  ]
 },
 "昼": {
  "pinyin": "zhòu",
  "english": "",
  "words": [
   {
    "w": "昼夜",
    "p": "zhòuyè",
    "en": "day and night, period of 24 hours, continuously, without stop"
   }
  ]
 },
 "拄": {
  "pinyin": "zhǔ",
  "english": "to lean on, to prop on"
 },
 "撰": {
  "pinyin": "zhuàn",
  "english": "",
  "words": [
   {
    "w": "撰写",
    "p": "zhuànxiě",
    "en": "write"
   }
  ]
 },
 "浊": {
  "pinyin": "zhuó",
  "english": "",
  "words": [
   {
    "w": "混浊",
    "p": "hùnzhuó",
    "en": "turbid, muddy, dirty"
   }
  ]
 },
 "揍": {
  "pinyin": "zòu",
  "english": "to beat up, to break to pieces"
 },
 "癌": {
  "pinyin": "ái",
  "english": "tumor, sarcoma, leukemia, cancerous, melanoma, malignant tumor, cancer, malignancy, neoplasm, carcinoma",
  "words": [
   {
    "w": "癌症",
    "p": "áizhèng",
    "en": "carcinomatosis, cancer"
   }
  ]
 },
 "芭": {
  "pinyin": "bā",
  "english": "",
  "words": [
   {
    "w": "芭蕾",
    "p": "bālěi",
    "en": "ballet (loanword)"
   }
  ]
 },
 "靶": {
  "pinyin": "bǎ",
  "english": "",
  "words": [
   {
    "w": "靶子",
    "p": "bǎzi",
    "en": "target"
   }
  ]
 },
 "颁": {
  "pinyin": "bān",
  "english": "",
  "words": [
   {
    "w": "颁发",
    "p": "bānfā",
    "en": "issue, promulgate, award"
   },
   {
    "w": "颁奖",
    "p": "bān jiǎng",
    "en": "present reward/honor"
   },
   {
    "w": "颁布",
    "p": "bānbù",
    "en": "to issue, to proclaim, to enact (laws, decrees etc)"
   }
  ]
 },
 "邦": {
  "pinyin": "bāng",
  "english": "",
  "words": [
   {
    "w": "联邦",
    "p": "liánbāng",
    "en": "federacy, union, federal, nation, confederation, commonwealth, federation, confederacy"
   }
  ]
 },
 "谤": {
  "pinyin": "bàng",
  "english": "",
  "words": [
   {
    "w": "诽谤",
    "p": "fěibàng",
    "en": "to slander, to libel"
   }
  ]
 },
 "镑": {
  "pinyin": "bàng",
  "english": "",
  "words": [
   {
    "w": "英镑",
    "p": "yīngbàng",
    "en": "pound sterling"
   }
  ]
 },
 "煲": {
  "pinyin": "bāo",
  "english": "to cook slowly over a low flame, pot, saucepan"
 },
 "狈": {
  "pinyin": "bèi",
  "english": "",
  "words": [
   {
    "w": "狼狈",
    "p": "lángbèi",
    "en": "in a difficult situation, to cut a sorry figure, scoundrel! (derog.)"
   }
  ]
 },
 "绷": {
  "pinyin": "běng",
  "english": "to stretch, taut, to tie, to bind, to have a taut face",
  "words": [
   {
    "w": "绷带",
    "p": "bēngdài",
    "en": "bandage (loanword)"
   }
  ]
 },
 "痹": {
  "pinyin": "bì",
  "english": "",
  "words": [
   {
    "w": "麻痹",
    "p": "mábì",
    "en": "paralysis, palsy, numbness, to benumb, (fig.) to lull, negligent, apathetic"
   }
  ]
 },
 "贬": {
  "pinyin": "biǎn",
  "english": "",
  "words": [
   {
    "w": "贬值",
    "p": "biǎn zhí",
    "en": "to become devaluated, to devaluate, to depreciate"
   }
  ]
 },
 "辫": {
  "pinyin": "biàn",
  "english": "",
  "words": [
   {
    "w": "辫子",
    "p": "biànzi",
    "en": "plait, braid, pigtail, a mistake or shortcoming that may be exploited by an opponent, handle, CL:根[gen1],條|条[tiao2]"
   }
  ]
 },
 "飙": {
  "pinyin": "biāo",
  "english": "",
  "words": [
   {
    "w": "飙升",
    "p": "biāoshēng",
    "en": "to rise rapidly, to soar"
   }
  ]
 },
 "缤": {
  "pinyin": "bīn",
  "english": "",
  "words": [
   {
    "w": "缤纷",
    "p": "bīnfēn",
    "en": "vast and various, rich and diverse"
   }
  ]
 },
 "秉": {
  "pinyin": "bǐng",
  "english": "",
  "words": [
   {
    "w": "秉承",
    "p": "bǐngchéng",
    "en": "to take orders, to receive commands, to carry on (a tradition)"
   }
  ]
 },
 "驳": {
  "pinyin": "bó",
  "english": "",
  "words": [
   {
    "w": "驳回",
    "p": "bóhuí",
    "en": "to reject, to turn down, to overrule"
   },
   {
    "w": "反驳",
    "p": "fǎnbó",
    "en": "refute, retort, negate"
   }
  ]
 },
 "舶": {
  "pinyin": "bó",
  "english": "",
  "words": [
   {
    "w": "船舶",
    "p": "chuánbó",
    "en": "shipping, boats"
   }
  ]
 },
 "膊": {
  "pinyin": "bo",
  "english": "",
  "words": [
   {
    "w": "胳膊",
    "p": "gēbo",
    "en": "arm, CL:隻|只[zhi1],條|条[tiao2],雙|双[shuang1]"
   }
  ]
 },
 "睬": {
  "pinyin": "cǎi",
  "english": "",
  "words": [
   {
    "w": "理睬",
    "p": "lǐcǎi",
    "en": "to heed, to pay attention to"
   }
  ]
 },
 "糙": {
  "pinyin": "cāo",
  "english": "",
  "words": [
   {
    "w": "粗糙",
    "p": "cūcāo",
    "en": "crude, gruff, rough, coarse"
   }
  ]
 },
 "诧": {
  "pinyin": "chà",
  "english": "",
  "words": [
   {
    "w": "诧异",
    "p": "chàyì",
    "en": "flabbergasted, astonished"
   },
   {
    "w": "惊诧",
    "p": "jīngchà",
    "en": "to be surprised, to be amazed, to be stunned"
   }
  ]
 },
 "馋": {
  "pinyin": "chán",
  "english": "gluttonous, greedy, to have a craving"
 },
 "铲": {
  "pinyin": "chǎn",
  "english": "to shovel, to remove, spade, shovel",
  "words": [
   {
    "w": "铲子",
    "p": "chǎnzi",
    "en": "shovel, spade, trowel, spatula (kitchen utensil), CL:把[ba3]"
   }
  ]
 },
 "阐": {
  "pinyin": "chǎn",
  "english": "",
  "words": [
   {
    "w": "阐述",
    "p": "chǎnshù",
    "en": "to expound (a position), to elaborate (on a topic), to treat (a subject)"
   }
  ]
 },
 "猖": {
  "pinyin": "chāng",
  "english": "",
  "words": [
   {
    "w": "猖狂",
    "p": "chāngkuáng",
    "en": "savage, furious"
   }
  ]
 },
 "钞": {
  "pinyin": "chāo",
  "english": "",
  "words": [
   {
    "w": "钞票",
    "p": "chāopiào",
    "en": "bank note, paper money, bill"
   }
  ]
 },
 "辰": {
  "pinyin": "chén",
  "english": "",
  "words": [
   {
    "w": "诞辰",
    "p": "dànchén",
    "en": "birthday"
   }
  ]
 },
 "逞": {
  "pinyin": "chěng",
  "english": "",
  "words": [
   {
    "w": "逞能",
    "p": "chěng néng",
    "en": "to show off one's ability, to boast one's merits"
   },
   {
    "w": "逞强",
    "p": "chěng qiáng",
    "en": "to show off, to try to be brave"
   }
  ]
 },
 "畴": {
  "pinyin": "chóu",
  "english": "",
  "words": [
   {
    "w": "范畴",
    "p": "fànchóu",
    "en": "category"
   }
  ]
 },
 "畜": {
  "pinyin": "chù",
  "english": "",
  "words": [
   {
    "w": "牲畜",
    "p": "shēngchù",
    "en": "domesticated animals, livestock"
   }
  ]
 },
 "踹": {
  "pinyin": "chuài",
  "english": "to kick, to trample, to tread on"
 },
 "炊": {
  "pinyin": "chuī",
  "english": "",
  "words": [
   {
    "w": "野炊",
    "p": "yěchuī",
    "en": "Picnic"
   }
  ]
 },
 "醇": {
  "pinyin": "chún",
  "english": "",
  "words": [
   {
    "w": "醇厚",
    "p": "chúnhòu",
    "en": "mellow and rich, simple and kind"
   }
  ]
 },
 "绰": {
  "pinyin": "chuò",
  "english": "",
  "words": [
   {
    "w": "绰号",
    "p": "chuòhào",
    "en": "nickname"
   },
   {
    "w": "阔绰",
    "p": "kuòchuò",
    "en": "ostentatious, extravagant, liberal with money"
   }
  ]
 },
 "簇": {
  "pinyin": "cù",
  "english": "",
  "words": [
   {
    "w": "簇拥",
    "p": "cùyōng",
    "en": "to crowd around, to escort"
   }
  ]
 },
 "窜": {
  "pinyin": "cuàn",
  "english": "to flee, to scuttle, to exile or banish, to amend or edit"
 },
 "粹": {
  "pinyin": "cuì",
  "english": "",
  "words": [
   {
    "w": "纯粹",
    "p": "chúncuì",
    "en": "unmixed, unalloyed, pure, unadulterated"
   }
  ]
 },
 "磋": {
  "pinyin": "cuō",
  "english": "",
  "words": [
   {
    "w": "磋商",
    "p": "cuōshāng",
    "en": "to consult, to discuss seriously, to negotiate, to confer, negotiations, consultations"
   }
  ]
 },
 "蹬": {
  "pinyin": "dēng",
  "english": "to step on, to tread on, to wear (shoes), (slang) to dump (sb), Taiwan pr. [deng4]"
 },
 "颠": {
  "pinyin": "diān",
  "english": "",
  "words": [
   {
    "w": "颠倒",
    "p": "diāndǎo",
    "en": "to turn upside down, to reverse, back to front, confused, deranged, crazy"
   },
   {
    "w": "颠覆",
    "p": "diānfù",
    "en": "overturn, subvert"
   }
  ]
 },
 "迭": {
  "pinyin": "dié",
  "english": "",
  "words": [
   {
    "w": "迭起",
    "p": "diéqǐ",
    "en": "continuously arising, to arise repeatedly"
   }
  ]
 },
 "谍": {
  "pinyin": "dié",
  "english": "",
  "words": [
   {
    "w": "间谍",
    "p": "jiàndié",
    "en": "spy"
   }
  ]
 },
 "碟": {
  "pinyin": "dié",
  "english": "",
  "words": [
   {
    "w": "光碟",
    "p": "guāngdié",
    "en": "compact disk, compact disc, CD ROM, compact_disk, CD"
   }
  ]
 },
 "董": {
  "pinyin": "dǒng",
  "english": "",
  "words": [
   {
    "w": "董事",
    "p": "dǒngshì",
    "en": "director, trustee"
   },
   {
    "w": "董事会",
    "p": "dǒngshìhuì",
    "en": "board, board of directors, board of administration, syndicate, directorate, board of regents, board of trustees, board_of_directors, directory"
   },
   {
    "w": "董事长",
    "p": "dǒngshìzhǎng",
    "en": "board chair"
   },
   {
    "w": "古董",
    "p": "gǔdǒng",
    "en": "old fogey, curio, antique, virtu, vertu, bygone, bric-a-brac"
   }
  ]
 },
 "逗": {
  "pinyin": "dòu",
  "english": "to stay, to stop, to tease (play with), amusing, short pause in reading aloud, equivalent to comma (also written 讀|读[dou4])"
 },
 "舵": {
  "pinyin": "duò",
  "english": "",
  "words": [
   {
    "w": "舵手",
    "p": "duòshǒu",
    "en": "helmsman"
   }
  ]
 },
 "讹": {
  "pinyin": "é",
  "english": "",
  "words": [
   {
    "w": "讹诈",
    "p": "ézhà",
    "en": "to extort under false pretenses, to blackmail, to bluff, to defraud"
   }
  ]
 },
 "遏": {
  "pinyin": "è",
  "english": "",
  "words": [
   {
    "w": "遏制",
    "p": "èzhì",
    "en": "to check, to contain, to hold back, to keep within limits, to constrain, to restrain"
   }
  ]
 },
 "饵": {
  "pinyin": "r",
  "english": "",
  "words": [
   {
    "w": "诱饵",
    "p": "yòuěr",
    "en": "bait"
   }
  ]
 },
 "芳": {
  "pinyin": "fāng",
  "english": "",
  "words": [
   {
    "w": "芬芳",
    "p": "fēnfāng",
    "en": "perfume, fragrant"
   }
  ]
 },
 "肪": {
  "pinyin": "fáng",
  "english": "",
  "words": [
   {
    "w": "脂肪",
    "p": "zhīfáng",
    "en": "grease, fat, axunge, adipose, fatness, avoirdupois, fattiness, adipose tissue, fatty tissue"
   }
  ]
 },
 "绯": {
  "pinyin": "fēi",
  "english": "",
  "words": [
   {
    "w": "绯闻",
    "p": "fēiwén",
    "en": "sex scandal"
   }
  ]
 },
 "诽": {
  "pinyin": "fěi",
  "english": "",
  "words": [
   {
    "w": "诽谤",
    "p": "fěibàng",
    "en": "to slander, to libel"
   }
  ]
 },
 "芬": {
  "pinyin": "fēn",
  "english": "",
  "words": [
   {
    "w": "芬芳",
    "p": "fēnfāng",
    "en": "perfume, fragrant"
   }
  ]
 },
 "粪": {
  "pinyin": "fèn",
  "english": "manure, dung",
  "words": [
   {
    "w": "粪便",
    "p": "fènbiàn",
    "en": "excrement, feces, night soil"
   }
  ]
 },
 "讽": {
  "pinyin": "fěng",
  "english": "",
  "words": [
   {
    "w": "讽刺",
    "p": "fěngcì",
    "en": "satirize, mock"
   }
  ]
 },
 "袱": {
  "pinyin": "fu",
  "english": "",
  "words": [
   {
    "w": "包袱",
    "p": "bāofu",
    "en": "cloth wrapper, bundle wrapped in cloth, burden, millstone round one's neck, punch line (in cross-talk)"
   }
  ]
 },
 "辐": {
  "pinyin": "fú",
  "english": "",
  "words": [
   {
    "w": "辐射",
    "p": "fúshè",
    "en": "radiancy, Geigers, radiation, radiant"
   }
  ]
 },
 "钙": {
  "pinyin": "gài",
  "english": "atomic number 20, calcium, Ca, calcic"
 },
 "胳": {
  "pinyin": "gē",
  "english": "",
  "words": [
   {
    "w": "胳膊",
    "p": "gēbo",
    "en": "arm, CL:隻|只[zhi1],條|条[tiao2],雙|双[shuang1]"
   }
  ]
 },
 "耿": {
  "pinyin": "gěng",
  "english": "",
  "words": [
   {
    "w": "耿直",
    "p": "gěngzhí",
    "en": "honest, frank, candid"
   }
  ]
 },
 "钩": {
  "pinyin": "gōu",
  "english": "to hook, to sew, to crochet, hook, check mark or tick, window catch",
  "words": [
   {
    "w": "钩子",
    "p": "gōuzi",
    "en": "hook"
   },
   {
    "w": "挂钩",
    "p": "guàgōu",
    "en": "hook (on which to hang sth), to couple, to link together, to establish contact with, hook, coupling links (e.g. between two railway coaches)"
   }
  ]
 },
 "辜": {
  "pinyin": "gū",
  "english": "",
  "words": [
   {
    "w": "辜负",
    "p": "gūfù",
    "en": "to fail to live up (to expectations), unworthy (of trust), to let down, to betray (hopes), to disappoint"
   },
   {
    "w": "无辜",
    "p": "wúgū",
    "en": "innocent, innocence, not guilty (law)"
   }
  ]
 },
 "闺": {
  "pinyin": "guī",
  "english": "",
  "words": [
   {
    "w": "闺女",
    "p": "guīnü",
    "en": "maiden, unmarried woman, daughter"
   }
  ]
 },
 "酣": {
  "pinyin": "hān",
  "english": "",
  "words": [
   {
    "w": "酣畅",
    "p": "hānchàng",
    "en": "unrestrained, cheerful lack of inhibition, esp. for drinking or sleeping, to drink with abandon"
   },
   {
    "w": "酣睡",
    "p": "hānshuì",
    "en": "to sleep soundly, to fall into a deep sleep"
   }
  ]
 },
 "焊": {
  "pinyin": "hàn",
  "english": "to weld, to solder, variant of 焊[han4]"
 },
 "阂": {
  "pinyin": "hé",
  "english": "",
  "words": [
   {
    "w": "隔阂",
    "p": "géhé",
    "en": "misunderstanding, estrangement, (language etc) barrier"
   }
  ]
 },
 "赫": {
  "pinyin": "hè",
  "english": "",
  "words": [
   {
    "w": "赫然",
    "p": "hèrán",
    "en": "with astonishment, with a shock, awe-inspiringly, impressively, furiously (angry)"
   },
   {
    "w": "显赫",
    "p": "xiǎnhè",
    "en": "illustrious, celebrated"
   }
  ]
 },
 "轰": {
  "pinyin": "hōng",
  "english": "explosion, bang, boom, rumble, to attack, to shoo away, to expel",
  "words": [
   {
    "w": "轰动",
    "p": "hōngdòng",
    "en": "to cause a sensation, to create a stir in (a place), commotion, controversy"
   },
   {
    "w": "轰炸",
    "p": "hōngzhà",
    "en": "bomb"
   }
  ]
 },
 "猾": {
  "pinyin": "huá",
  "english": "",
  "words": [
   {
    "w": "狡猾",
    "p": "jiǎohuá",
    "en": "crafty, cunning, sly"
   }
  ]
 },
 "焕": {
  "pinyin": "huàn",
  "english": "",
  "words": [
   {
    "w": "焕发",
    "p": "huànfā",
    "en": "to shine, to glow, to irradiate, to flash"
   },
   {
    "w": "容光焕发",
    "p": "róngguāng-huànfā",
    "en": "face glowing (idiom), looking radiant, all smiles"
   }
  ]
 },
 "痪": {
  "pinyin": "huàn",
  "english": "",
  "words": [
   {
    "w": "瘫痪",
    "p": "tānhuàn",
    "en": "paralysis, be paralyzed (body, transportation, etc)"
   }
  ]
 },
 "讳": {
  "pinyin": "hui",
  "english": "",
  "words": [
   {
    "w": "忌讳",
    "p": "jìhui",
    "en": "taboo, to avoid as taboo, to abstain from"
   }
  ]
 },
 "秽": {
  "pinyin": "huì",
  "english": "",
  "words": [
   {
    "w": "污秽",
    "p": "wūhuì",
    "en": "nasty, sordid, filthy"
   }
  ]
 },
 "豁": {
  "pinyin": "huō",
  "english": "to play Chinese finger-guessing game, opening, stake all, sacrifice, crack, slit, clear, open, exempt (from), liberal-minded",
  "words": [
   {
    "w": "豁出去",
    "p": "huō chuqu",
    "en": "to throw caution to the wind, to press one's luck, to go for broke"
   },
   {
    "w": "豁达",
    "p": "huòdá",
    "en": "optimistic, sanguine, generous, magnanimous, open-minded"
   }
  ]
 },
 "霍": {
  "pinyin": "huò",
  "english": "",
  "words": [
   {
    "w": "霍乱",
    "p": "huòluàn",
    "en": "cholera"
   }
  ]
 },
 "讥": {
  "pinyin": "jī",
  "english": "",
  "words": [
   {
    "w": "讥笑",
    "p": "jīxiào",
    "en": "to sneer"
   }
  ]
 },
 "缉": {
  "pinyin": "jī",
  "english": "",
  "words": [
   {
    "w": "通缉",
    "p": "tōngjī",
    "en": "to order the arrest of sb as criminal, to list as wanted"
   }
  ]
 },
 "畸": {
  "pinyin": "jī",
  "english": "",
  "words": [
   {
    "w": "畸形",
    "p": "jīxíng",
    "en": "deformity, abnormality"
   }
  ]
 },
 "稽": {
  "pinyin": "ji",
  "english": "",
  "words": [
   {
    "w": "滑稽",
    "p": "huáji",
    "en": "comical, funny, amusing, old pr. [gu3 ji1], huaji, a form of comedy performance popular in Shanghai, Jiangsu and Zhejiang"
   }
  ]
 },
 "贱": {
  "pinyin": "jiàn",
  "english": "inexpensive, lowly"
 },
 "礁": {
  "pinyin": "jiāo",
  "english": "",
  "words": [
   {
    "w": "礁石",
    "p": "jiāoshí",
    "en": "reef"
   }
  ]
 },
 "狡": {
  "pinyin": "jiǎo",
  "english": "",
  "words": [
   {
    "w": "狡猾",
    "p": "jiǎohuá",
    "en": "crafty, cunning, sly"
   }
  ]
 },
 "矫": {
  "pinyin": "jiǎo",
  "english": "",
  "words": [
   {
    "w": "矫正",
    "p": "jiǎozhèng",
    "en": "to correct, to rectify (e.g. a physical defect such as hearing or vision), to cure, rectification, correction, to straighten"
   }
  ]
 },
 "缴": {
  "pinyin": "jiǎo",
  "english": "turn_in, hand in, hand over/in, capture, pay, in, shell_out, hand over",
  "words": [
   {
    "w": "缴费",
    "p": "jiǎofèi",
    "en": "to pay a fee"
   },
   {
    "w": "缴纳",
    "p": "jiǎonà",
    "en": "to pay (taxes etc)"
   }
  ]
 },
 "酵": {
  "pinyin": "jiào",
  "english": "",
  "words": [
   {
    "w": "发酵",
    "p": "fājiào",
    "en": "to ferment, fermentation"
   }
  ]
 },
 "诫": {
  "pinyin": "jiè",
  "english": "",
  "words": [
   {
    "w": "告诫",
    "p": "gàojiè",
    "en": "to warn, to admonish"
   }
  ]
 },
 "谨": {
  "pinyin": "jǐn",
  "english": "",
  "words": [
   {
    "w": "谨慎",
    "p": "jǐnshèn",
    "en": "cautious, circumspect"
   },
   {
    "w": "严谨",
    "p": "yánjǐn",
    "en": "rigorous, strict, compact, well-knit"
   }
  ]
 },
 "窘": {
  "pinyin": "jiǒng",
  "english": "",
  "words": [
   {
    "w": "窘迫",
    "p": "jiǒngpò",
    "en": "poverty-stricken, very poor, hard-pressed, in a predicament, embarrassed"
   }
  ]
 },
 "灸": {
  "pinyin": "jiǔ",
  "english": "",
  "words": [
   {
    "w": "针灸",
    "p": "zhēnjiǔ",
    "en": "acupuncture and moxibustion, to give or have acupuncture and moxibustion"
   }
  ]
 },
 "炬": {
  "pinyin": "jù",
  "english": "",
  "words": [
   {
    "w": "火炬",
    "p": "huǒjù",
    "en": "a torch, CL:把[ba3]"
   }
  ]
 },
 "锯": {
  "pinyin": "jù",
  "english": "variant of 鋦|锔[ju1], a saw, to cut with a saw"
 },
 "诀": {
  "pinyin": "jué",
  "english": "",
  "words": [
   {
    "w": "诀别",
    "p": "juébié",
    "en": "to bid farewell, to part (usually with little hope of meeting again)"
   },
   {
    "w": "诀窍",
    "p": "juéqiào",
    "en": "secret, trick, knack, key"
   },
   {
    "w": "秘诀",
    "p": "mìjué",
    "en": "secret know-how, key (to longevity), secret (of happiness), recipe (for success)"
   }
  ]
 },
 "爵": {
  "pinyin": "jué",
  "english": "",
  "words": [
   {
    "w": "爵士",
    "p": "juéshì",
    "en": "knight, Sir, (loanword) jazz"
   }
  ]
 },
 "竣": {
  "pinyin": "jùn",
  "english": "",
  "words": [
   {
    "w": "竣工",
    "p": "jùn gōng",
    "en": "to complete a project"
   }
  ]
 },
 "苛": {
  "pinyin": "kē",
  "english": "",
  "words": [
   {
    "w": "苛刻",
    "p": "kēkè",
    "en": "harsh, severe, demanding"
   }
  ]
 },
 "筐": {
  "pinyin": "kuāng",
  "english": "basket, CL:隻|只[zhi1]"
 },
 "馈": {
  "pinyin": "kuì",
  "english": "",
  "words": [
   {
    "w": "反馈",
    "p": "fǎnkuì",
    "en": "to send back information, feedback"
   },
   {
    "w": "回馈",
    "p": "huíkuì",
    "en": "reward, feedback"
   }
  ]
 },
 "蜡": {
  "pinyin": "là",
  "english": "candle, wax",
  "words": [
   {
    "w": "蜡烛",
    "p": "làzhú",
    "en": "candle"
   }
  ]
 },
 "缆": {
  "pinyin": "lǎn",
  "english": "",
  "words": [
   {
    "w": "光缆",
    "p": "guānglǎn",
    "en": "optical cable"
   },
   {
    "w": "缆车",
    "p": "lǎnchē",
    "en": "cable car"
   }
  ]
 },
 "隶": {
  "pinyin": "lì",
  "english": "",
  "words": [
   {
    "w": "奴隶",
    "p": "núlì",
    "en": "slave"
   }
  ]
 },
 "辽": {
  "pinyin": "liáo",
  "english": "",
  "words": [
   {
    "w": "辽阔",
    "p": "liáokuò",
    "en": "vast, extensive"
   }
  ]
 },
 "赁": {
  "pinyin": "lìn",
  "english": "",
  "words": [
   {
    "w": "租赁",
    "p": "zūlìn",
    "en": "to rent, to lease, to hire"
   }
  ]
 },
 "瘤": {
  "pinyin": "liú",
  "english": "",
  "words": [
   {
    "w": "肿瘤",
    "p": "zhǒngliú",
    "en": "tumor"
   }
  ]
 },
 "遛": {
  "pinyin": "liù",
  "english": "to stroll, to walk (an animal)"
 },
 "陋": {
  "pinyin": "lòu",
  "english": "",
  "words": [
   {
    "w": "丑陋",
    "p": "chǒulòu",
    "en": "ugly"
   },
   {
    "w": "孤陋寡闻",
    "p": "gūlòu-guǎwén",
    "en": "ignorant and inexperienced, ill-informed and narrow-minded"
   },
   {
    "w": "简陋",
    "p": "jiǎnlòu",
    "en": "simple and crude"
   }
  ]
 },
 "虏": {
  "pinyin": "lǔ",
  "english": "",
  "words": [
   {
    "w": "俘虏",
    "p": "fúlǔ",
    "en": "captive"
   }
  ]
 },
 "鹿": {
  "pinyin": "lù",
  "english": "cervine, deer, European elk, elk, moose, Alces alces, cervid"
 },
 "螺": {
  "pinyin": "luó",
  "english": "",
  "words": [
   {
    "w": "螺丝",
    "p": "luósī",
    "en": "screw"
   }
  ]
 },
 "迈": {
  "pinyin": "mài",
  "english": "to take a step, to stride",
  "words": [
   {
    "w": "迈进",
    "p": "màijìn",
    "en": "forge ahead, stride forward, advance with big strides"
   },
   {
    "w": "年迈",
    "p": "niánmài",
    "en": "old, aged"
   }
  ]
 },
 "蛮": {
  "pinyin": "mán",
  "english": "pretty, very, quite, more or less, pretty much, fairly, rather, somewhat, to some extent",
  "words": [
   {
    "w": "野蛮",
    "p": "yěmán",
    "en": "barbarous, uncivilized"
   }
  ]
 },
 "蔓": {
  "pinyin": "màn",
  "english": "",
  "words": [
   {
    "w": "蔓延",
    "p": "mànyán",
    "en": "spread out, extend"
   }
  ]
 },
 "芒": {
  "pinyin": "máng",
  "english": "",
  "words": [
   {
    "w": "光芒",
    "p": "guāngmáng",
    "en": "ray_of_light, rays of light, brilliant ray, radiance"
   }
  ]
 },
 "莽": {
  "pinyin": "mǎng",
  "english": "",
  "words": [
   {
    "w": "鲁莽",
    "p": "lǔmǎng",
    "en": "hot-headed, impulsive, reckless"
   }
  ]
 },
 "髦": {
  "pinyin": "máo",
  "english": "",
  "words": [
   {
    "w": "时髦",
    "p": "shímáo",
    "en": "in vogue, fashionable"
   }
  ]
 },
 "缅": {
  "pinyin": "miǎn",
  "english": "",
  "words": [
   {
    "w": "缅怀",
    "p": "miǎnhuái",
    "en": "to commemorate, to recall fondly, to think of the past"
   }
  ]
 },
 "蔑": {
  "pinyin": "miè",
  "english": "",
  "words": [
   {
    "w": "轻蔑",
    "p": "qīngmiè",
    "en": "to contempt, to disdain, pejorative"
   }
  ]
 },
 "谬": {
  "pinyin": "miù",
  "english": "",
  "words": [
   {
    "w": "荒谬",
    "p": "huāngmiù",
    "en": "absurd, preposterous"
   }
  ]
 },
 "魔": {
  "pinyin": "mó",
  "english": "",
  "words": [
   {
    "w": "魔鬼",
    "p": "móguǐ",
    "en": "devil"
   },
   {
    "w": "魔术",
    "p": "móshù",
    "en": "magic"
   }
  ]
 },
 "陌": {
  "pinyin": "mò",
  "english": "",
  "words": [
   {
    "w": "陌生",
    "p": "mòshēng",
    "en": "strange, unfamiliar"
   }
  ]
 },
 "牡": {
  "pinyin": "mǔ",
  "english": "",
  "words": [
   {
    "w": "牡丹",
    "p": "mǔdan",
    "en": "Mudan District of Heze City 菏澤市|菏泽市[He2 ze2 Shi4], Shandong, Mutan township in Pingtung County 屏東縣|屏东县[Ping2 dong1 Xian4], Taiwan, tree peony (Paeonia suffruticosa)"
   }
  ]
 },
 "馁": {
  "pinyin": "něi",
  "english": "",
  "words": [
   {
    "w": "气馁",
    "p": "qìněi",
    "en": "to be discouraged"
   }
  ]
 },
 "逆": {
  "pinyin": "nì",
  "english": "contrary, opposite, backwards, to go against, to oppose, to betray, to rebel",
  "words": [
   {
    "w": "叛逆",
    "p": "pànnì",
    "en": "to rebel, to revolt, a rebel"
   }
  ]
 },
 "黏": {
  "pinyin": "nián",
  "english": "sticky, glutinous, to adhere, to stick"
 },
 "纽": {
  "pinyin": "niǔ",
  "english": "",
  "words": [
   {
    "w": "纽带",
    "p": "niǔdài",
    "en": "tie, link, bond"
   },
   {
    "w": "纽扣",
    "p": "niǔkòu",
    "en": "button"
   },
   {
    "w": "枢纽",
    "p": "shūniǔ",
    "en": "hub (e.g. of traffic network), hinge, pivot, fulcrum"
   }
  ]
 },
 "烹": {
  "pinyin": "pēng",
  "english": "",
  "words": [
   {
    "w": "烹调",
    "p": "pēngtiáo",
    "en": "to cook, cooking"
   }
  ]
 },
 "菩": {
  "pinyin": "pú",
  "english": "",
  "words": [
   {
    "w": "菩萨",
    "p": "púsà",
    "en": "Buddhist idol, a term applied to a kindhearted person, kindhearted person, Bodhisattva, joss, Buddha, Boddhisatva"
   }
  ]
 },
 "迄": {
  "pinyin": "qì",
  "english": "",
  "words": [
   {
    "w": "迄今为止",
    "p": "qìjīnwéizhǐ",
    "en": "so far, up to now, still (not)"
   },
   {
    "w": "迄今",
    "p": "qìjīn",
    "en": "so far, to date, until now"
   }
  ]
 },
 "虔": {
  "pinyin": "qián",
  "english": "",
  "words": [
   {
    "w": "虔诚",
    "p": "qiánchéng",
    "en": "pious, devout, sincere"
   }
  ]
 },
 "钳": {
  "pinyin": "qián",
  "english": "",
  "words": [
   {
    "w": "钳子",
    "p": "qiánzi",
    "en": "pliers, pincers, tongs, forceps, vise, clamp, claw (of a crab etc), CL:把[ba3], (dialect) earring"
   }
  ]
 },
 "谴": {
  "pinyin": "qiǎn",
  "english": "",
  "words": [
   {
    "w": "谴责",
    "p": "qiǎnzé",
    "en": "condemn, denounce, censure"
   }
  ]
 },
 "钦": {
  "pinyin": "qīn",
  "english": "",
  "words": [
   {
    "w": "钦佩",
    "p": "qīnpèi",
    "en": "to admire, to look up to, to respect sb greatly"
   }
  ]
 },
 "顷": {
  "pinyin": "qǐng",
  "english": "",
  "words": [
   {
    "w": "公顷",
    "p": "gōngqǐng",
    "en": "m.[standard]"
   }
  ]
 },
 "饶": {
  "pinyin": "ráo",
  "english": "surname Rao, rich, abundant, exuberant, to add for free, to throw in as bonus, to spare, to forgive, despite, although",
  "words": [
   {
    "w": "饶恕",
    "p": "ráoshù",
    "en": "to forgive, to pardon, to spare"
   }
  ]
 },
 "臊": {
  "pinyin": "sào",
  "english": "",
  "words": [
   {
    "w": "害臊",
    "p": "hài sào",
    "en": "to be bashful, to feel ashamed"
   }
  ]
 },
 "煽": {
  "pinyin": "shān",
  "english": "",
  "words": [
   {
    "w": "煽动",
    "p": "shāndòng",
    "en": "to incite, to instigate"
   }
  ]
 },
 "膳": {
  "pinyin": "shàn",
  "english": "",
  "words": [
   {
    "w": "膳食",
    "p": "shànshí",
    "en": "meal"
   }
  ]
 },
 "赡": {
  "pinyin": "shàn",
  "english": "",
  "words": [
   {
    "w": "赡养",
    "p": "shànyǎng",
    "en": "to support, to provide support for, to maintain"
   }
  ]
 },
 "绅": {
  "pinyin": "shēn",
  "english": "",
  "words": [
   {
    "w": "绅士",
    "p": "shēnshì",
    "en": "gentleman"
   }
  ]
 },
 "肾": {
  "pinyin": "shèn",
  "english": "kidney"
 },
 "蚀": {
  "pinyin": "shí",
  "english": "",
  "words": [
   {
    "w": "腐蚀",
    "p": "fǔshí",
    "en": "corrosion, to corrode (degrade chemically), to rot, corruption"
   }
  ]
 },
 "赎": {
  "pinyin": "shú",
  "english": "to redeem, to ransom"
 },
 "祀": {
  "pinyin": "si",
  "english": "",
  "words": [
   {
    "w": "祭祀",
    "p": "jìsi",
    "en": "offer sacrifices to gods/ancestors"
   }
  ]
 },
 "讼": {
  "pinyin": "sòng",
  "english": "",
  "words": [
   {
    "w": "诉讼",
    "p": "sùsòng",
    "en": "lawsuit"
   }
  ]
 },
 "颂": {
  "pinyin": "sòng",
  "english": "",
  "words": [
   {
    "w": "歌颂",
    "p": "gēsòng",
    "en": "to sing the praises of, to extol, to eulogize"
   }
  ]
 },
 "艘": {
  "pinyin": "sōu",
  "english": "m.[general]"
 },
 "酥": {
  "pinyin": "sū",
  "english": "flaky pastry, crunchy, limp, soft, silky"
 },
 "髓": {
  "pinyin": "suǐ",
  "english": "",
  "words": [
   {
    "w": "精髓",
    "p": "jīngsuǐ",
    "en": "marrow, pith, quintessence, essence"
   }
  ]
 },
 "遂": {
  "pinyin": "suì",
  "english": "",
  "words": [
   {
    "w": "遂心",
    "p": "suì xīn",
    "en": "to one's liking"
   }
  ]
 },
 "瘫": {
  "pinyin": "tān",
  "english": "paralyzed",
  "words": [
   {
    "w": "瘫痪",
    "p": "tānhuàn",
    "en": "paralysis, be paralyzed (body, transportation, etc)"
   }
  ]
 },
 "痰": {
  "pinyin": "tán",
  "english": "phlegm, spittle"
 },
 "秃": {
  "pinyin": "tū",
  "english": "bald, blunt"
 },
 "腕": {
  "pinyin": "wàn",
  "english": "",
  "words": [
   {
    "w": "大腕儿",
    "p": "dàwànr5",
    "en": "Big wrist"
   },
   {
    "w": "手腕",
    "p": "shǒuwàn",
    "en": "wrist"
   }
  ]
 },
 "纬": {
  "pinyin": "wěi",
  "english": "",
  "words": [
   {
    "w": "纬度",
    "p": "wěidù",
    "en": "latitude"
   }
  ]
 },
 "萎": {
  "pinyin": "wěi",
  "english": "",
  "words": [
   {
    "w": "萎缩",
    "p": "wěisuō",
    "en": "wither, shrivel, shrink, sag, atrophy"
   }
  ]
 },
 "瘟": {
  "pinyin": "wēn",
  "english": "",
  "words": [
   {
    "w": "瘟疫",
    "p": "wēnyì",
    "en": "epidemic, plague, pestilence, diseased"
   }
  ]
 },
 "紊": {
  "pinyin": "wěn",
  "english": "",
  "words": [
   {
    "w": "紊乱",
    "p": "wěnluàn",
    "en": "disorder, chaos"
   }
  ]
 },
 "锡": {
  "pinyin": "xī",
  "english": "tin (chemistry), to bestow, to confer, to grant, Taiwan pr. [xi2]"
 },
 "瞎": {
  "pinyin": "xiā",
  "english": "blind, groundlessly, foolishly, to no purpose"
 },
 "辖": {
  "pinyin": "xiá",
  "english": "",
  "words": [
   {
    "w": "管辖",
    "p": "guǎnxiá",
    "en": "to administer, to have jurisdiction (over)"
   }
  ]
 },
 "纤": {
  "pinyin": "xiān",
  "english": "",
  "words": [
   {
    "w": "化纤",
    "p": "huàxiān",
    "en": "synthetic fiber"
   },
   {
    "w": "纤维",
    "p": "xiānwéi",
    "en": "fiber, staple"
   }
  ]
 },
 "贤": {
  "pinyin": "xián",
  "english": "",
  "words": [
   {
    "w": "圣贤",
    "p": "shèngxián",
    "en": "a sage, wise and holy man, virtuous ruler, Buddhist lama, wine"
   }
  ]
 },
 "馅": {
  "pinyin": "xiàn",
  "english": "",
  "words": [
   {
    "w": "馅儿",
    "p": "xiànr5",
    "en": "stuffing, forcemeat, filling, erhua variant of 餡|馅[xian4]"
   }
  ]
 },
 "腺": {
  "pinyin": "xiàn",
  "english": "gland"
 },
 "翔": {
  "pinyin": "xiáng",
  "english": "",
  "words": [
   {
    "w": "飞翔",
    "p": "fēixiáng",
    "en": "to circle in the air, to soar"
   }
  ]
 },
 "巷": {
  "pinyin": "",
  "english": "lane; alley",
  "words": [
   {
    "w": "大街小巷",
    "p": "dàjiē-xiǎoxiàng",
    "en": "great streets and small alleys (idiom), everywhere in the city"
   }
  ]
 },
 "萧": {
  "pinyin": "xiāo",
  "english": "",
  "words": [
   {
    "w": "萧条",
    "p": "xiāotiáo",
    "en": "bleak, desolate, (economic) depression or slump"
   }
  ]
 },
 "肖": {
  "pinyin": "xiào",
  "english": "",
  "words": [
   {
    "w": "肖像",
    "p": "xiàoxiàng",
    "en": "portrait (painting, photo etc), (in a general sense) representation of a person, likeness"
   }
  ]
 },
 "邪": {
  "pinyin": "xié",
  "english": "demonic, iniquitous, nefarious, evil, unhealthy influences that cause disease (Chinese medicine)",
  "words": [
   {
    "w": "改邪归正",
    "p": "gǎixié-guīzhèng",
    "en": "to mend one's ways (idiom), to turn over a new leaf"
   },
   {
    "w": "邪恶",
    "p": "xiéè",
    "en": "sinister, vicious, wicked, evil"
   }
  ]
 },
 "芯": {
  "pinyin": "xīn",
  "english": "",
  "words": [
   {
    "w": "芯片",
    "p": "xīnpiàn",
    "en": "computer chip, microchip"
   }
  ]
 },
 "馨": {
  "pinyin": "xīn",
  "english": "",
  "words": [
   {
    "w": "温馨",
    "p": "wēnxīn",
    "en": "warm and fragrant"
   }
  ]
 },
 "衅": {
  "pinyin": "xìn",
  "english": "",
  "words": [
   {
    "w": "挑衅",
    "p": "tiǎoxìn",
    "en": "to provoke, provocation"
   }
  ]
 },
 "猩": {
  "pinyin": "xīng",
  "english": "",
  "words": [
   {
    "w": "猩猩",
    "p": "xīngxing",
    "en": "orangutan"
   }
  ]
 },
 "酗": {
  "pinyin": "xù",
  "english": "",
  "words": [
   {
    "w": "酗酒",
    "p": "xùjiǔ",
    "en": "heavy drinking, to get drunk, to drink to excess"
   }
  ]
 },
 "絮": {
  "pinyin": "xù",
  "english": "",
  "words": [
   {
    "w": "絮叨",
    "p": "xùdao",
    "en": "long-winded, garrulous, to talk endlessly without getting to the point"
   }
  ]
 },
 "玄": {
  "pinyin": "xuán",
  "english": "black, mysterious",
  "words": [
   {
    "w": "玄机",
    "p": "xuánjī",
    "en": "profound theory (in Daoism and Buddhism), mysterious principles"
   }
  ]
 },
 "芽": {
  "pinyin": "yá",
  "english": "bud, sprout",
  "words": [
   {
    "w": "萌芽",
    "p": "méngyá",
    "en": "to sprout (lit. or fig.), to bud, to germinate, germ, seed, bud"
   }
  ]
 },
 "讶": {
  "pinyin": "yà",
  "english": "",
  "words": [
   {
    "w": "惊讶",
    "p": "jīngyà",
    "en": "amazed, astounded"
   }
  ]
 },
 "阎": {
  "pinyin": "yán",
  "english": "",
  "words": [
   {
    "w": "阎王",
    "p": "Yánwang",
    "en": "same as 閻羅王|阎罗王, Yama, King of Hell, translation of Sanskrit: Yama Raja"
   }
  ]
 },
 "衍": {
  "pinyin": "yǎn",
  "english": "",
  "words": [
   {
    "w": "衍生",
    "p": "yǎnshēng",
    "en": "derive, form"
   }
  ]
 },
 "窑": {
  "pinyin": "yáo",
  "english": "kiln, oven, coal pit, cave dwelling, (coll.) brothel, variant of 窯|窑[yao2]"
 },
 "绎": {
  "pinyin": "yì",
  "english": "",
  "words": [
   {
    "w": "络绎不绝",
    "p": "luòyì-bùjué",
    "en": "continuously, in an endless stream (idiom)"
   },
   {
    "w": "演绎",
    "p": "yǎnyì",
    "en": "(of a story etc) to unfold, to play out, to develop (a technique etc), to enact, (logic) to deduce, to infer"
   }
  ]
 },
 "疫": {
  "pinyin": "yì",
  "english": "",
  "words": [
   {
    "w": "防疫",
    "p": "fángyì",
    "en": "disease prevention, protection against epidemic"
   },
   {
    "w": "免疫",
    "p": "miǎnyì",
    "en": "immunize, immune"
   },
   {
    "w": "瘟疫",
    "p": "wēnyì",
    "en": "epidemic, plague, pestilence, diseased"
   },
   {
    "w": "疫苗",
    "p": "yìmiáo",
    "en": "vaccine"
   }
  ]
 },
 "裔": {
  "pinyin": "yì",
  "english": "",
  "words": [
   {
    "w": "后裔",
    "p": "hòuyì",
    "en": "descendant"
   },
   {
    "w": "华裔",
    "p": "huáyì",
    "en": "foreign citizen of Ch. origin"
   }
  ]
 },
 "荫": {
  "pinyin": "yīn",
  "english": "",
  "words": [
   {
    "w": "树荫",
    "p": "shùyīn",
    "en": "shade of a tree"
   }
  ]
 },
 "瘾": {
  "pinyin": "yǐn",
  "english": "addiction, craving",
  "words": [
   {
    "w": "过瘾",
    "p": "guò yǐn",
    "en": "to satisfy a craving, to get a kick out of sth, gratifying, immensely enjoyable, satisfying, fulfilling"
   },
   {
    "w": "上瘾",
    "p": "shàng yǐn",
    "en": "to get into a habit, to become addicted"
   }
  ]
 },
 "莹": {
  "pinyin": "yíng",
  "english": "",
  "words": [
   {
    "w": "晶莹",
    "p": "jīngyíng",
    "en": "sparkling and translucent"
   }
  ]
 },
 "踊": {
  "pinyin": "yǒng",
  "english": "",
  "words": [
   {
    "w": "踊跃",
    "p": "yǒngyuè",
    "en": "enthusiastical, leap, jump, eager"
   }
  ]
 },
 "诱": {
  "pinyin": "yòuě",
  "english": "",
  "words": [
   {
    "w": "引诱",
    "p": "yǐnyòu",
    "en": "lure, seduce"
   },
   {
    "w": "诱饵",
    "p": "yòuěr",
    "en": "bait"
   },
   {
    "w": "诱惑",
    "p": "yòuhuò",
    "en": "tempt, seduce, lure"
   },
   {
    "w": "诱发",
    "p": "yòufā",
    "en": "to induce, to cause, to elicit, to trigger"
   },
   {
    "w": "诱人",
    "p": "yòurén",
    "en": "attractive, alluring, captivating, to attract, to captivate"
   }
  ]
 },
 "逾": {
  "pinyin": "yú",
  "english": "",
  "words": [
   {
    "w": "逾期",
    "p": "yú qī",
    "en": "to be overdue, to fail to meet a deadline, to be behind in doing sth"
   }
  ]
 },
 "舆": {
  "pinyin": "yú",
  "english": "",
  "words": [
   {
    "w": "舆论",
    "p": "yúlùn",
    "en": "sense, vox_populi, popular opinion, public opinion, opinion, public_opinion, consensus, vox populi"
   }
  ]
 },
 "驭": {
  "pinyin": "yù",
  "english": "",
  "words": [
   {
    "w": "驾驭",
    "p": "jiàyù",
    "en": "to urge on (of horse), to drive, to steer, to handle, to manage, to master, to dominate"
   }
  ]
 },
 "陨": {
  "pinyin": "yǔn",
  "english": "",
  "words": [
   {
    "w": "陨石",
    "p": "yǔnshí",
    "en": "meteorite, meteor, aerolite, stony meteorite"
   }
  ]
 },
 "酝": {
  "pinyin": "yùn",
  "english": "",
  "words": [
   {
    "w": "酝酿",
    "p": "yùnniàng",
    "en": "(of alcohol) to ferment, (of a crisis) to be brewing, to mull over (an issue), to hold exploratory discussions"
   }
  ]
 },
 "蕴": {
  "pinyin": "yùn",
  "english": "",
  "words": [
   {
    "w": "底蕴",
    "p": "dǐyùn",
    "en": "inside information, concrete details"
   },
   {
    "w": "蕴涵",
    "p": "yùnhán",
    "en": "to contain, to accumulate, to embrace, implicit condition, implication, entailment"
   },
   {
    "w": "蕴藏",
    "p": "yùncáng",
    "en": "to hold in store, to contain (untapped reserves etc)"
   }
  ]
 },
 "赃": {
  "pinyin": "zāng",
  "english": "",
  "words": [
   {
    "w": "分赃",
    "p": "fēn zāng",
    "en": "to share the booty, to divide ill-gotten gains"
   }
  ]
 },
 "葬": {
  "pinyin": "zàng",
  "english": "to bury (the dead), to inter",
  "words": [
   {
    "w": "陪葬",
    "p": "péizàng",
    "en": "to be buried with or next to dead person (of deceased's partner, or of funerary objects)"
   },
   {
    "w": "葬礼",
    "p": "zànglǐ",
    "en": "burial, funeral"
   }
  ]
 },
 "灶": {
  "pinyin": "zào",
  "english": "",
  "words": [
   {
    "w": "炉灶",
    "p": "lúzào",
    "en": "stove"
   }
  ]
 },
 "皂": {
  "pinyin": "zào",
  "english": "",
  "words": [
   {
    "w": "肥皂",
    "p": "féizào",
    "en": "soap, CL:塊|块[kuai4],條|条[tiao2]"
   }
  ]
 },
 "诈": {
  "pinyin": "zhà",
  "english": "",
  "words": [
   {
    "w": "讹诈",
    "p": "ézhà",
    "en": "to extort under false pretenses, to blackmail, to bluff, to defraud"
   },
   {
    "w": "奸诈",
    "p": "jiānzhà",
    "en": "treachery, devious, a rogue"
   },
   {
    "w": "欺诈",
    "p": "qīzhà",
    "en": "to cheat"
   },
   {
    "w": "敲诈",
    "p": "qiāozhà",
    "en": "to rip off, to extort (money), extortion, blackmail"
   },
   {
    "w": "诈骗",
    "p": "zhàpiàn",
    "en": "to defraud, to swindle, to blackmail"
   }
  ]
 },
 "粘": {
  "pinyin": "zhān",
  "english": "glutinous, sticky, to stick, to adhere, variant of 黏[nian2], to glue, to stick, to paste"
 },
 "蘸": {
  "pinyin": "zhàn",
  "english": "to dip in (ink, sauce etc)"
 },
 "肇": {
  "pinyin": "zhào",
  "english": "",
  "words": [
   {
    "w": "肇事",
    "p": "zhàoshì",
    "en": "to cause trouble, to provoke a disturbance"
   }
  ]
 },
 "贞": {
  "pinyin": "zhēn",
  "english": "",
  "words": [
   {
    "w": "忠贞",
    "p": "zhōngzhēn",
    "en": "loyal and dependable"
   }
  ]
 },
 "筝": {
  "pinyin": "zheng",
  "english": "",
  "words": [
   {
    "w": "风筝",
    "p": "fēngzheng",
    "en": "kite"
   }
  ]
 },
 "蒸": {
  "pinyin": "zhēng",
  "english": "to evaporate, (of cooking) to steam, torch made from hemp stalks or bamboo (old), finely chopped firewood (old)"
 },
 "芝": {
  "pinyin": "zhī",
  "english": "",
  "words": [
   {
    "w": "芝麻",
    "p": "zhīma",
    "en": "sesame (seed)"
   },
   {
    "w": "芝士",
    "p": "zhīshì",
    "en": "cheese (loanword)"
   }
  ]
 },
 "窒": {
  "pinyin": "zhì",
  "english": "",
  "words": [
   {
    "w": "窒息",
    "p": "zhìxī",
    "en": "to choke, to stifle, to suffocate"
   }
  ]
 },
 "瞩": {
  "pinyin": "zhǔ",
  "english": "",
  "words": [
   {
    "w": "举世瞩目",
    "p": "jǔshì-zhǔmù",
    "en": "to receive worldwide attention"
   },
   {
    "w": "瞩目",
    "p": "zhǔmù",
    "en": "fix eyes on"
   }
  ]
 },
 "贮": {
  "pinyin": "zhù",
  "english": "",
  "words": [
   {
    "w": "贮藏",
    "p": "zhùcáng",
    "en": "to store up, to hoard, deposits"
   }
  ]
 },
 "铸": {
  "pinyin": "zhù",
  "english": "",
  "words": [
   {
    "w": "铸造",
    "p": "zhùzào",
    "en": "to cast (pour metal into a mold)"
   }
  ]
 },
 "灼": {
  "pinyin": "zhuó",
  "english": "",
  "words": [
   {
    "w": "灼热",
    "p": "zhuórè",
    "en": "burning hot, scorching, worried"
   }
  ]
 },
 "酌": {
  "pinyin": "zhuó",
  "english": "",
  "words": [
   {
    "w": "酌情",
    "p": "zhuóqíng",
    "en": "to use discretion, to take circumstances into account, to make allowances pertinent to a situation"
   }
  ]
 },
 "粽": {
  "pinyin": "zòng",
  "english": "",
  "words": [
   {
    "w": "粽子",
    "p": "zòngzi",
    "en": "glutinous rice and choice of filling wrapped in leaves and boiled"
   }
  ]
 },
 "沐": {
  "pinyin": "",
  "english": "wash; bathe",
  "words": [
   {
    "w": "沐浴露",
    "p": "mùyùlù",
    "en": "shower gel"
   }
  ]
 },
 "暮": {
  "pinyin": "",
  "english": "dusk; evening",
  "words": [
   {
    "w": "朝三暮四",
    "p": "zhāosān-mùsì",
    "en": "lit. say three in the morning but four in the evening (idiom), to change sth that is already settled upon, indecisive, to blow hot and cold"
   }
  ]
 },
 "菇": {
  "pinyin": "",
  "english": "mushroom",
  "words": [
   {
    "w": "蘑菇",
    "p": "mógu",
    "en": "mushroom, to pester, to dawdle"
   }
  ]
 },
 "饥": {
  "pinyin": "",
  "english": "hungry",
  "words": [
   {
    "w": "饥饿",
    "p": "jīè",
    "en": "hunger, starvation, famine"
   },
   {
    "w": "忍饥挨饿",
    "p": "rěnjī-áiè",
    "en": "starving, famished"
   }
  ]
 },
 "蘑": {
  "pinyin": "",
  "english": "mushroom",
  "words": [
   {
    "w": "蘑菇",
    "p": "mógu",
    "en": "mushroom, to pester, to dawdle"
   }
  ]
 },
 "彬": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "彬彬有礼",
    "p": "bīnbīn-yǒulǐ",
    "en": "refined and courteous, urbane"
   }
  ]
 },
 "嫦": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "嫦娥",
    "p": "Chángé",
    "en": "Chang'e, the lady in the moon (Chinese mythology), one of the Chang'e series of PRC lunar spacecraft"
   }
  ]
 },
 "娥": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "嫦娥",
    "p": "Chángé",
    "en": "Chang'e, the lady in the moon (Chinese mythology), one of the Chang'e series of PRC lunar spacecraft"
   }
  ]
 },
 "冯": {
  "pinyin": "",
  "english": ""
 },
 "丐": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "乞丐",
    "p": "qǐgài",
    "en": "beggar"
   }
  ]
 },
 "冈": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "山冈",
    "p": "shāngāng",
    "en": "mound, small hill"
   }
  ]
 },
 "卦": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "八卦",
    "p": "bāguà",
    "en": "the eight divinatory trigrams of the Book of Changes 易經|易经[Yi4 jing1], gossip, gossipy"
   }
  ]
 },
 "兢": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "兢兢业业",
    "p": "jīngjīng-yèyè",
    "en": "cautious and conscientious"
   }
  ]
 },
 "吭": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "一声不吭",
    "p": "yīshēngbùkēng",
    "en": "to not say a word"
   }
  ]
 },
 "寥": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "寥寥无几",
    "p": "liáoliáo-wújǐ",
    "en": "just a very few (idiom), tiny number, not many at all, You count them on your fingers."
   }
  ]
 },
 "吕": {
  "pinyin": "",
  "english": ""
 },
 "乓": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "乒乓球",
    "p": "pīngpāngqiú",
    "en": "table tennis, ping-pong, table tennis ball, CL:個|个[ge4]"
   }
  ]
 },
 "乒": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "乒乓球",
    "p": "pīngpāngqiú",
    "en": "table tennis, ping-pong, table tennis ball, CL:個|个[ge4]"
   }
  ]
 },
 "宋": {
  "pinyin": "",
  "english": ""
 },
 "伊": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "伊斯兰教",
    "p": "Yīsīlánjiào",
    "en": "Islam"
   }
  ]
 },
 "澳": {
  "pinyin": "",
  "english": ""
 },
 "涤": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "洗涤剂",
    "p": "xǐdíjì",
    "en": "cleaning agent, detergent"
   }
  ]
 },
 "沽": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "沽名钓誉",
    "p": "gūmíng-diàoyù",
    "en": "to angle for fame (idiom), to fish for compliments"
   }
  ]
 },
 "沪": {
  "pinyin": "",
  "english": ""
 },
 "潘": {
  "pinyin": "",
  "english": ""
 },
 "拋": {
  "pinyin": "",
  "english": ""
 },
 "浦": {
  "pinyin": "",
  "english": ""
 },
 "攘": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "熙熙攘攘",
    "p": "xīxī-rǎngrǎng",
    "en": "bustling with activity (idiom)"
   }
  ]
 },
 "曙": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "曙光",
    "p": "shǔguāng",
    "en": "dawn, fig. the dawn of a new era"
   }
  ]
 },
 "斯": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "穆斯林",
    "p": "Mùsīlín",
    "en": "Muslim"
   },
   {
    "w": "伊斯兰教",
    "p": "Yīsīlánjiào",
    "en": "Islam"
   }
  ]
 },
 "滔": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "滔滔不绝",
    "p": "tāotāo-bùjué",
    "en": "unceasing torrent (idiom), talking non-stop, gabbling forty to the dozen"
   }
  ]
 },
 "渝": {
  "pinyin": "",
  "english": ""
 },
 "隘": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "狭隘",
    "p": "xiáài",
    "en": "narrow, tight, narrow minded, lacking in experience"
   }
  ]
 },
 "邓": {
  "pinyin": "",
  "english": ""
 },
 "蒂": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "根深蒂固",
    "p": "gēnshēn-dìgù",
    "en": "deep-rooted (problem etc)"
   }
  ]
 },
 "甸": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "沉甸甸",
    "p": "chéndiàndiàn",
    "en": "heavy"
   }
  ]
 },
 "盹": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "打盹儿",
    "p": "dǎ dǔnr5",
    "en": "to doze off, erhua variant of 打盹[da3 dun3]"
   }
  ]
 },
 "膏": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "牙膏",
    "p": "yágāo",
    "en": "toothpaste, CL:管[guan3]"
   }
  ]
 },
 "躬": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "鞠躬",
    "p": "jūgōng",
    "en": "to bow, (literary) to bend down"
   }
  ]
 },
 "郭": {
  "pinyin": "",
  "english": ""
 },
 "骇": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "骇人听闻",
    "p": "hàirén-tīngwén",
    "en": "shocking, horrifying, atrocious, terrible"
   }
  ]
 },
 "韩": {
  "pinyin": "",
  "english": ""
 },
 "鞠": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "鞠躬",
    "p": "jūgōng",
    "en": "to bow, (literary) to bend down"
   }
  ]
 },
 "钧": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "千钧一发",
    "p": "qiānjūn-yīfà",
    "en": "a thousand pounds hangs by a thread (idiom), imminent peril, a matter of life or death"
   }
  ]
 },
 "磊": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "光明磊落",
    "p": "guāngmíng-lěiluò",
    "en": "open and candid (idiom), straightforward and upright"
   }
  ]
 },
 "玫": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "玫瑰",
    "p": "méigui",
    "en": "rosebush, rose"
   }
  ]
 },
 "穆": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "穆斯林",
    "p": "Mùsīlín",
    "en": "Muslim"
   }
  ]
 },
 "鹏": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "鹏程万里",
    "p": "péngchéng-wànlǐ",
    "en": "the fabled roc flies ten thousand miles (idiom), one's future prospects are brilliant"
   }
  ]
 },
 "萍": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "萍水相逢",
    "p": "píngshuǐ-xiāngféng",
    "en": "strangers coming together by chance (idiom)"
   }
  ]
 },
 "秦": {
  "pinyin": "",
  "english": ""
 },
 "矢": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "有的放矢",
    "p": "yǒudì-fàngshǐ",
    "en": "Title"
   }
  ]
 },
 "蜀": {
  "pinyin": "",
  "english": ""
 },
 "熙": {
  "pinyin": "",
  "english": "",
  "words": [
   {
    "w": "熙熙攘攘",
    "p": "xīxī-rǎngrǎng",
    "en": "bustling with activity (idiom)"
   }
  ]
 },
 "袁": {
  "pinyin": "",
  "english": ""
 },
 "粤": {
  "pinyin": "",
  "english": ""
 }
};
